apiVersion: v1
kind: Service
metadata:
  name: nano-1-svc
  labels:
    app: nano-1
spec:
  ports:
    - port: 80
  selector:
    app: nano-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano-1
spec:
  selector:
    matchLabels:
      app: nano-1
  replicas: 5
  template:
    metadata:
      labels:
        app: nano-1
    spec:
      containers:
      - name: nano-1-1
        image: nano-1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1