kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-server
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-ci-server: "true"
rules: [] # Rules are automatically filled in by the controller manager.
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-deploy
  labels:
    rbac.authorization.k8s.io/aggregate-to-ci-server: "true"
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "services", "pods"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-server-concourse
subjects:
- kind: ServiceAccount
  name: concourse
  namespace: default
roleRef:
  kind: ClusterRole
  name: ci-server
  apiGroup: ""
