---
resources:
- name: repo-release
  type: github-release
  source:
    user: AdamHawtin
    repository: concourse-testing

- name: repo-pre-release
  type: github-release
  source:
    user: AdamHawtin
    repository: concourse-testing
    release: false
    pre_release: true

jobs:
- name: preprod-pre-release-deploy
  serial_groups: [preprod_deploys]
  serial: true
  plan:
  - get: repo-pre-release
    trigger: true
    params:
      include_source_tarball: true
  - task: Get pre release source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: repo-pre-release
      outputs:
      - name: pre-release-source
      run:
        path: sh
        args:
        - -exc
        - |
          tar -xzf repo-pre-release/source.tar.gz -C pre-release-source --strip-components=1
          ls -a pre-release-source
  - task: Check pre-prelease source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: pre-release-source
      run:
        path: sh
        args:
        - -exc
        - |
          ls -a pre-release-source

- name: preprod-deploy
  serial_groups: [preprod_deploys]
  serial: true
  plan:
  - get: repo-release
    trigger: true
    params:
      include_source_tarball: true
  - task: Get release source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: repo-release
      outputs:
      - name: release-source
      run:
        path: sh
        args:
        - -exc
        - |
          tar -xzf repo-release/source.tar.gz -C release-source --strip-components=1
          ls -a release-source
  - task: Check pre-prod release source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: release-source
      run:
        path: sh
        args:
        - -exc
        - |
          ls -a release-source

- name: prod-deploy
  serial: true
  plan:
  - get: repo-release
    trigger: true
    params:
      include_source_tarball: true
    passed: [preprod-deploy]
  - task: Get release source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: repo-release
      outputs:
      - name: release-source
      run:
        path: sh
        args:
        - -exc
        - |
          tar -xzf repo-release/source.tar.gz -C release-source --strip-components=1
          ls -a release-source
  - task: Check release source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: release-source
      run:
        path: sh
        args:
        - -exc
        - |
          ls -a release-source
