---
resources:
- name: repo-release
  type: github-release
  source:
    user: AdamHawtin
    repository: concourse-testing

- name: repo-pre-release
  type: github-release
  source:
    user: AdamHawtin
    repository: concourse-testing
    release: false
    pre_release: true

- name: concourse-testing-repo
  type: git
  source:
    uri: https://github.com/AdamHawtin/concourse-testing.git

jobs:
- name: preprod-pre-release-deploy
  serial_groups: [preprod_deploys]
  serial: true
  plan:
  - get: repo-pre-release
    trigger: true
    params:
      include_source_tarball: true
  - get: concourse-testing-repo
  - task: Get pre release source
    file: concourse-testing-repo/extract-source-from-release.yml
    input_mapping: { release-resource: repo-pre-release }
    output_mapping: { release-source: pre-release-source }
  - task: Check pre-prelease source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: pre-release-source
      run:
        path: sh
        args:
        - -exc
        - |
          ls -a pre-release-source

- name: preprod-deploy
  serial_groups: [preprod_deploys]
  serial: true
  plan:
  - get: repo-release
    trigger: true
    params:
      include_source_tarball: true
  - get: concourse-testing-repo
  - task: Get release source
    file: concourse-testing-repo/extract-source-from-release.yml
    input_mapping: { release-resource: repo-release }
    output_mapping: { release-source: release-source }
  - task: Check pre-prod release source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: release-source
      run:
        path: sh
        args:
        - -exc
        - |
          ls -a release-source

- name: prod-deploy
  serial: true
  plan:
  - get: repo-release
    trigger: true
    params:
      include_source_tarball: true
    passed: [preprod-deploy]
  - get: concourse-testing-repo
  - task: Get release source
    file: concourse-testing-repo/extract-source-from-release.yml
    input_mapping: { release-resource: repo-release }
    output_mapping: { release-source: release-source }
  - task: Check release source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: release-source
      run:
        path: sh
        args:
        - -exc
        - |
          ls -a release-source
