---
resources:
- name: test-repo-source
  type: git
  source:
    uri: https://github.com/AdamHawtin/concourse-testing.git
    branch: master

- name: test-repo-release
  type: github-release
  source:
    user: AdamHawtin
    repository: concourse-testing

- name: test-repo-preprod-release
  type: github-release
  source:
    user: AdamHawtin
    repository: concourse-testing
    release: true
    pre_release: true

jobs:
- name: test-pre-release-job
  serial: true
  plan:
  - get: test-repo-source
  - get: test-repo-release
  - get: test-repo-preprod-release
    trigger: true
    params:
      include_source_tarball: true
  - task: Get pre release source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: test-repo-preprod-release
      outputs:
      - name: test-preprod-release-source
      run:
        path: sh
        args:
        - -exc
        - |
          mkdir test-preprod-release-source
          tar -xzf test-repo-preprod-release/source.tar.gz -C test-preprod-release-source --strip-components=1
          ls -a test-preprod-release-source
  - task: Check pre-prelease source
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      inputs:
      - name: test-preprod-release-source
      run:
        path: sh
        args:
        - -exc
        - |
          ls -a test-preprod-release-source

- name: test-release-job
  serial: true
  plan:
  - get: test-repo-release
    trigger: true
    passed: [test-pre-release-job]
  - get: test-repo-source
  - task: Hello My Friends!
    file: test-repo-source/hello-my-friends.yml
