apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano-3
spec:
  selector:
    matchLabels:
      app: nano-3
  replicas: 5
  template:
    metadata:
      labels:
        app: nano-3
    spec:
      containers:
      - name: nano-3-1
        image: nano-1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1